# Generated by Django 6.0.6 on 2026-06-15 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pci_api', '0002_transaction_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.BigIntegerField(db_index=True, help_text='pk from pci_transctions at the tine of archiving')),
                ('transaction_ref', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pan_encrypted', models.TextField()),
                ('expiry_encrypted', models.TextField()),
                ('pan_masked', models.CharField(max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archived_reason', models.TextField(default='', max_length=255)),
            ],
            options={
                'db_table': 'pci_transactions_archive',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner'], name='idx_tx_owner'),
        ),
        migrations.AddField(
            model_name='transactionarchive',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transactionarchive',
            index=models.Index(fields=['email'], name='idx_arch_email'),
        ),
        migrations.AddIndex(
            model_name='transactionarchive',
            index=models.Index(fields=['status'], name='idx_arch_status'),
        ),
        migrations.AddIndex(
            model_name='transactionarchive',
            index=models.Index(fields=['archived_at'], name='idx_arch_archived_at'),
        ),
        migrations.AddIndex(
            model_name='transactionarchive',
            index=models.Index(fields=['owner'], name='idx_arch_owner'),
        ),
    ]
