# Generated by Django 6.0.6 on 2026-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pci_api', '0003_transactionarchive_alter_transaction_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
