# Generated by Django 6.0.6 on 2026-07-14 09:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0003_user_email_verification_token_user_face_id_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('RECEIVABLE', 'Receivable (collect incoming Paystack payments)'), ('PAYABLE', 'Payable (hold funds earmarked for outgoing Paystack payments)')], max_length=15, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_wallets',
            },
        ),
        migrations.CreateModel(
            name='ProviderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('provider_ref', models.CharField(blank=True, max_length=128)),
                ('direction', models.CharField(choices=[('FUNDING', 'Funding (customer -> receivable -> customer wallet)'), ('WITHDRAWAL', 'Withdrawal (customer wallet -> payable -> customer bank)')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10)),
                ('recipient_code', models.CharField(blank=True, max_length=64)),
                ('bank_code', models.CharField(blank=True, max_length=11)),
                ('account_no', models.CharField(blank=True, max_length=10)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('paystack_data', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'provider_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
