# Generated by Django 6.0.6 on 2026-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertransaction',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
    ]
