# Generated by Django 6.0.6 on 2026-06-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_kyc_verified',
            new_name='is_kyc_validated',
        ),
    ]
