# Generated by Django 6.0.6 on 2026-07-06 22:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_is_kyc_verified_user_is_kyc_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='face_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_tier',
            field=models.IntegerField(choices=[(1, 'Tier 1 - Registered'), (2, 'Tier 2 - Email and phone verified'), (3, 'Tier 3 - BVN and faceId verified')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verification_token',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=15),
        ),
    ]
