# Generated by Django 6.0.6 on 2026-06-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration_months', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active (Disbursed)'), ('CLOSED', 'Closed (Fully Repaid)'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=10)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_no', models.PositiveIntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=10)),
                ('transaction_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'loan_repayments',
                'ordering': ['due_date'],
                'unique_together': {('loan', 'instalment_no')},
            },
        ),
    ]
