# Generated by Django 6.0.6 on 2026-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='user_loan_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
