# Generated by Django 6.0.6 on 2026-06-29 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_user_loan_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loanapplication',
            unique_together={('user', 'user_loan_number')},
        ),
    ]
