# Generated by Django 6.0.6 on 2026-06-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='user_loan_number',
            field=models.PositiveIntegerField(),
        ),
    ]
